{% set version = "0.7.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggbeeswarm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/ggbeeswarm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggbeeswarm/ggbeeswarm_{{ version }}.tar.gz
  sha256: f41550335149bc2122fed0dd280d980cecd02ace79e042d5e03c1f102200ac92

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-beeswarm
    - r-ggplot2 >=2.0
    - r-vipor

  run:
    - r-base
    - r-beeswarm
    - r-ggplot2 >=2.0
    - r-vipor

test:
  commands:
    - $R -e "library('ggbeeswarm')"  # [not win]
    - "\"%R%\" -e \"library('ggbeeswarm')\""  # [win]

about:
  home: https://github.com/eclarke/ggbeeswarm
  license: GPL (>= 2)
  summary: Provides two methods of plotting categorical scatter plots such that the arrangement of points within a category reflects the density of data at that region, and avoids over-plotting.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
