{% set version = "0.7.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggbeeswarm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggbeeswarm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggbeeswarm/ggbeeswarm_{{ version }}.tar.gz
  sha256: fd7ca265bb892dde514d5f8d6a853fb8b32d7a673b05e9c8b50544a523299ce5

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-beeswarm
    - r-ggplot2 >=3.3.0
    - r-lifecycle
    - r-vipor
  run:
    - r-base
    - r-beeswarm
    - r-ggplot2 >=3.3.0
    - r-lifecycle
    - r-vipor

test:
  commands:
    - $R -e "library('ggbeeswarm')"           # [not win]
    - "\"%R%\" -e \"library('ggbeeswarm')\""  # [win]

about:
  home: https://github.com/eclarke/ggbeeswarm
  license: GPL-3.0-or-later
  summary: Provides two methods of plotting categorical scatter plots such that the arrangement of points within a category reflects the density of data at that region, and avoids over-plotting.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
