# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gVL6E2OSS0gpL+ee2naOHUOaCtwi1ZswKSEs7ueT2AY0Y8qlwpogGYw9uh9mjmvk1mBLJrHROifiaVpMXbYdj2EgTb9CKiqEQzgEZng1w8mqKisuR0EFzpo3SleQWjNDxipJS4+lIqC+A/1Dd62O8VzC/3Ch1QKvig74ti9ICXeqWhUyAbsmgDnoDex5EcGmlDFl6DbG8TR2euG47xhGo6mjH5eu/xDhqBo6eHLqhTKzr+Cq6VJ3b2tT91UZDD2HBRwevRSAF4595gb3y3QSyoHfGcqrjPfX9CTqiDTF0hCosYWmU9CzG9c7rmuG9K717G9arWKCCYsyzc0aVymCZ5J/vgKqw+OcD4lVHq6c8/eM1NCkbloxgEWE2iI3W6oPQZ0KRPANsajCZKx1j8psg0JLjtIM1jmnkzWxgpxikoEviojxSSQ/ccsYN+OEEtRafqyuGgyG/bbS56Gkyu4k52vBcTfx6RvVTZ6SAG+Yi9fJjE8ln2ClwjrjSH6l+mQ4zQiitdRNE0xQNNd+zuMKSpbTMwaMGH5yxRI1R3VmaNRbgxeZh6ZTrFrgZvE0cSNZqAEG0wCzsTzGXVGCzvlNmIqOoT3DA2d+4JqKEEhxi9rhHDCzqyI/sHm7kz02ts24VnVm4uchfWj0TbusdpJA2kKfEjniIBXsqWOA4nMLomM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
