travis:
  secure:
    BINSTAR_TOKEN: SaNUXdEzuXP8IAhvpVSQc5fF+9H2Ae/6xjqV8kflh+nJ74TYWq6Y+0SgSmOfWQuMeohqRtcJWr5ZKdp2owy9HfWXGPx98ZGjh/Po8qeL+1c979dwH7WqVKHbn6sdNVKfBZ+Nslf3CRQk/mCYRv+dTlZbirFIlPt1pRPqa4fA1qgtP7Wc0gbrtWoE2MAkAQNFIqhMKnZW4HfOT65ywdUcGPvOQxQGHvRcWIBlmOQFtqpCcSNKyDkLXYMg8syvTy/wCMWBwFgZvtz75qeliLretlAAIDEhq0nGjy6wP7KcbKXzh0HUZ6yElmX0PFe+tVAgj6lCm9UUS67ATYJviRFskNJwf4S64aUQLRwaDx5Ou7CS7zkRvy8lokQI908SZO8QbAGC6mMmxV3DdIZ8aIEwO5DJjztjYz2mfpMjR8LI9zeQu7FM6X8395NVZOY277gGHNE/0A4tQDiXbTWmzQ9lUDybcLzomW133lNZHK/sPI7kaCRT/BTGJJ1h4roRClrKokriTtTp/7mrlOAPBsyEoOCbAbdaDCQ/RiVHVbqOLzOzcJG05OUpmEyNR3O2Eu2HuC5tGqBfNzYAGNGUOhVpJj23lDh9sXt7EOObBCcymtQj29QAfP5V4CAXSh3TbCHH0E4iAvPY6RrXXJtuGpXef0LHMtoa1caXOz4M3TepqhU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
