appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gVL6E2OSS0gpL+ee2naOHUOaCtwi1ZswKSEs7ueT2AY0Y8qlwpogGYw9uh9mjmvk1mBLJrHROifiaVpMXbYdj2EgTb9CKiqEQzgEZng1w8mqKisuR0EFzpo3SleQWjNDxipJS4+lIqC+A/1Dd62O8VzC/3Ch1QKvig74ti9ICXeqWhUyAbsmgDnoDex5EcGmlDFl6DbG8TR2euG47xhGo6mjH5eu/xDhqBo6eHLqhTKzr+Cq6VJ3b2tT91UZDD2HBRwevRSAF4595gb3y3QSyoHfGcqrjPfX9CTqiDTF0hCosYWmU9CzG9c7rmuG9K717G9arWKCCYsyzc0aVymCZ5J/vgKqw+OcD4lVHq6c8/eM1NCkbloxgEWE2iI3W6oPQZ0KRPANsajCZKx1j8psg0JLjtIM1jmnkzWxgpxikoEviojxSSQ/ccsYN+OEEtRafqyuGgyG/bbS56Gkyu4k52vBcTfx6RvVTZ6SAG+Yi9fJjE8ln2ClwjrjSH6l+mQ4zQiitdRNE0xQNNd+zuMKSpbTMwaMGH5yxRI1R3VmaNRbgxeZh6ZTrFrgZvE0cSNZqAEG0wCzsTzGXVGCzvlNmIqOoT3DA2d+4JqKEEhxi9rhHDCzqyI/sHm7kz02ts24VnVm4uchfWj0TbusdpJA2kKfEjniIBXsqWOA4nMLomM=}
bot:
  automerge: true
